#!/bin/sh
# Self-bootstrapping PostgreSQL physical standby (read replica) of the prod
# primary. On first start (empty data dir) it clones the primary via
# pg_basebackup, then GENERATES its own postgresql.conf + pg_hba.conf and starts
# as a hot standby. On later starts it just resumes streaming. It is physically
# read-only, so it can never write back to prod.
#
# Why generate the configs: the prod primary is Debian-packaged Postgres, which
# keeps postgresql.conf / pg_hba.conf in /etc (OUTSIDE the data dir). pg_basebackup
# copies only the data dir, so the clone has no config files. We therefore build a
# minimal standby config, taking the parameters a standby must have >= the primary
# (max_connections, etc.) from the cloned CONTROL FILE via pg_controldata.
#
# Required env: PRIMARY_HOST, REPL_PASSWORD.
# Optional:     PRIMARY_PORT(5432), REPL_USER(replicator), REPL_SLOT(sandbox_replica).
# NOTE: use an alphanumeric REPL_PASSWORD (no ':' or '\') to avoid .pgpass escaping.
set -e

: "${PGDATA:=/var/lib/postgresql/data}"
: "${PRIMARY_PORT:=5432}"
: "${REPL_USER:=replicator}"
: "${REPL_SLOT:=sandbox_replica}"
: "${PGHOME:=/var/lib/postgresql}"

[ -n "$PRIMARY_HOST" ]  || { echo "[replica] PRIMARY_HOST is required" >&2; exit 1; }
[ -n "$REPL_PASSWORD" ] || { echo "[replica] REPL_PASSWORD is required" >&2; exit 1; }

# .pgpass so the walreceiver re-authenticates to the primary on EVERY restart
# (pg_basebackup -R writes primary_conninfo but NOT the password, by design).
PGPASS="$PGHOME/.pgpass"
printf '%s:%s:*:%s:%s\n' "$PRIMARY_HOST" "$PRIMARY_PORT" "$REPL_USER" "$REPL_PASSWORD" > "$PGPASS"
chown postgres:postgres "$PGPASS"
chmod 600 "$PGPASS"

mkdir -p "$PGDATA"
chown postgres:postgres "$PGDATA"
chmod 700 "$PGDATA"

if [ ! -s "$PGDATA/PG_VERSION" ]; then
    echo "[replica] empty data dir — cloning standby from ${PRIMARY_HOST}:${PRIMARY_PORT} (slot=${REPL_SLOT})..."
    rm -rf "${PGDATA:?}/"* 2>/dev/null || true
    # -R: standby.signal + primary_conninfo(+slot);  -Xs: stream WAL during backup
    su-exec postgres sh -c "PGPASSFILE='$PGPASS' pg_basebackup -h '$PRIMARY_HOST' -p '$PRIMARY_PORT' -U '$REPL_USER' -D '$PGDATA' -Fp -Xs -P -R -S '$REPL_SLOT'"

    # Pull the standby-must-match params from the cloned control file (these reflect
    # the PRIMARY's values; a standby must run with values >= the primary's).
    ctlval() { su-exec postgres pg_controldata "$PGDATA" | grep "$1" | awk -F: '{print $2}' | tr -dc '0-9'; }
    MAXCONN=$(ctlval 'max_connections setting');      : "${MAXCONN:=1000}"
    MAXWORK=$(ctlval 'max_worker_processes setting');  : "${MAXWORK:=64}"
    MAXSEND=$(ctlval 'max_wal_senders setting');       : "${MAXSEND:=10}"
    MAXPREP=$(ctlval 'max_prepared_xacts setting');    : "${MAXPREP:=0}"
    MAXLOCK=$(ctlval 'max_locks_per_xact setting');    : "${MAXLOCK:=256}"

    echo "[replica] generating standby config (max_connections=$MAXCONN max_worker_processes=$MAXWORK max_wal_senders=$MAXSEND max_prepared_transactions=$MAXPREP max_locks_per_transaction=$MAXLOCK)"
    cat > "$PGDATA/postgresql.conf" <<EOF
# Generated by the replica entrypoint — minimal hot-standby config.
listen_addresses = '*'
port = 5432
hot_standby = on
# Must MATCH the primary's loaded libraries for a physical standby to replay WAL.
shared_preload_libraries = 'timescaledb'
# Must be >= the primary's values (read from the cloned control file).
max_connections = $MAXCONN
max_worker_processes = $MAXWORK
max_wal_senders = $MAXSEND
max_prepared_transactions = $MAXPREP
max_locks_per_transaction = $MAXLOCK
EOF

    cat > "$PGDATA/pg_hba.conf" <<EOF
# Generated by the replica entrypoint. local trust (in-container admin) + scram
# for read connections from the sandbox bridge/VPC. Read-only standby.
local   all         all                     trust
host    all         all     127.0.0.1/32    scram-sha-256
host    all         all     ::1/128         scram-sha-256
host    all         all     10.0.0.0/8      scram-sha-256
host    all         all     172.16.0.0/12   scram-sha-256
host    all         all     192.168.0.0/16  scram-sha-256
host    replication all     0.0.0.0/0       scram-sha-256
EOF

    # Empty ident map (we use no ident user-mapping) — silences a harmless
    # "could not open file pg_ident.conf" warning on a Debian-sourced clone.
    : > "$PGDATA/pg_ident.conf"
    chown postgres:postgres "$PGDATA/postgresql.conf" "$PGDATA/pg_hba.conf" "$PGDATA/pg_ident.conf"
    echo "[replica] clone complete; starting as hot standby"
fi

# PGPASSFILE points the walreceiver at .pgpass regardless of HOME.
exec su-exec postgres env PGPASSFILE="$PGPASS" postgres -D "$PGDATA"
